# .github/workflows/android.yml
# https://github.com/marketplace/actions/gradle-command
name: Android unit tests
on:
  push:
    branches:
      - develop
      - master
    paths:
      - '!**.md'
      - '!**.adoc'
      - '!**/.gitignore'
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Copy fake google-services.json
        - run: cp -f .github/workflows/google-services.json app
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: githubAction
